id: examplo
title: Example ontology
github_org: user
repo: examplo
report_fail_on: ERROR
export_formats:
  - owl
components:
  products:
    - filename: pato.owl
      source: http://purl.obolibrary.org/obo/pato/pato-base.owl
robot_java_args: '-Xmx8G'
allow_equivalents: all
