id: examplo
title: Example ontology
github_org: user
repo: examplo
report_fail_on: ERROR
release_artefacts: 
  - full
export_formats:
  - owl
import_group:
  products:
    - id: envo 
    - id: exo
robot_java_args: '-Xmx8G'
allow_equivalents: all
