name: run tests
on: [push]
jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        name: setup python
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
      - name: run pytest
        run: |
          coverage erase
          pytest --cov=kg_obo --cov-report xml:coverage.xml
          coverage combine --append || true
          coverage report
          coverage xml
      - name: run mypy
        run: mypy --strict-optional kg_obo
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.KGCOVID19_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
